name: 'build & release plugin'

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write

    env:
      python_ver: 3.11

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ env.python_ver }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python_ver }}

    - name: Get plugin version from plugin.json
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'plugin.json'
        prop_path: 'Version'

    - name: Install dependencies into lib folder
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt -t ./lib --no-deps
        pip install gpsoauth requests -t ./lib

    - name: Create plugin archive
      run: |
        Compress-Archive -Path .\* -DestinationPath Flow.Launcher.Plugin.GoogleKeepFlow.zip -Force
      shell: powershell

    - name: Publish Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: 'Flow.Launcher.Plugin.GoogleKeepFlow.zip'
        tag_name: "v${{steps.version.outputs.prop}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
